services:
  base_net:
    environment:
      # Load in the ROS distro
      - ROS_DISTRO=$TARGET_ROS_DISTRO
    runtime: nvidia
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    container_name: base_net_${BUILD_TARGET}_dev
    image: alexnavtt/base_net:${BUILD_TARGET}
    build:
      context: ./..
      dockerfile: docker/Dockerfile
      ssh:
        - default
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
        NO_PROXY: $NO_PROXY
        http_proxy: $http_proxy
        https_proxy: $https_proxy
        no_proxy: $no_proxy
        ROS_DISTRO: $TARGET_ROS_DISTRO
        BUILD_TARGET: $BUILD_TARGET
        CUDA_VERSION: $TARGET_CUDA_VERSION

  base_net_runtime:
    extends: base_net
    volumes:
      - ${PWD}/..:/base_net
    environment:
      - SPOT_URDF_EXTRAS
      - BASE_NET_CONFIG

  generate_task_poses:
    extends: base_net_runtime
    container_name: base_net_task_pose_generation
    entrypoint: docker/entrypoints/generate_task_poses.sh

  calculate_ground_truth:
    extends: base_net_runtime
    container_name: base_net_ground_truth_calculation
    entrypoint: docker/entrypoints/calculate_ground_truth.sh

  train_model:
    extends: base_net_runtime
    container_name: base_net_training
    entrypoint: docker/entrypoints/train_model.sh

  generate_irm:
    extends: base_net_runtime
    container_name: base_net_inverse_reachability_map_generation
    entrypoint: docker/entrypoints/generate_irm.sh
