services:
  curobo:
    runtime: nvidia
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    container_name: place_net_curobo
    image: alexnavtt/place_net_curobo:$UBUNTU_VERSION
    build:
      dockerfile: curobo.Dockerfile
      args:
        # Build for CUDA version set by the user
        PLACE_NET_CUDA_ARCH: $CUDA_ARCH
        CUDA_VERSION: $TARGET_CUDA_VERSION
        UBUNTU_VERSION: $UBUNTU_VERSION

  jetson_curobo:
    runtime: nvidia
    container_name: place_net_curobo_jetson
    image: alexnavtt/place_net_curobo
    build:
      dockerfile: jetson-curobo.Dockerfile
      args:
        # Build for CUDA version set by the user
        CUDA_VERSION: $TARGET_CUDA_VERSION
        UBUNTU_VERSION: $UBUNTU_VERSION
