services:
  curobo:
    runtime: nvidia
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    container_name: place_net_curobo
    image: alexnavtt/place_net_curobo
    build:
      dockerfile: curobo.Dockerfile
      args:
        # Include proxy settings if working in a proxy-ed environment
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
        NO_PROXY: $NO_PROXY
        http_proxy: $http_proxy
        https_proxy: $https_proxy
        no_proxy: $no_proxy
        # Build for CUDA version set by the user
        CUDA_VERSION: $TARGET_CUDA_VERSION
