services:
  place_net:
    environment:
      # Load in the ROS distro
      - ROS_DISTRO=$TARGET_ROS_DISTRO
    runtime: nvidia
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    container_name: place_net_dev
    image: alexnavtt/place_net:${UBUNTU_VERSION}
    build:
      network: host
      context: ./../..
      dockerfile: place_net/docker/Dockerfile
      ssh:
        - default
      args:
        ROS_DISTRO: $TARGET_ROS_DISTRO
        GUEST_PACKAGES: $GUEST_PACKAGES
        GUEST_PACKAGE_NAMES: $GUEST_PACKAGE_NAMES
        UBUNTU_VERSION: $UBUNTU_VERSION

  place_net_runtime:
    extends: place_net
    container_name: place_net_runtime_dev
    volumes:
      # The main code base
      - ${PWD}/../place_net:/place_net/place_net
      # place_net_ros - Useful for debugging and development
      - ${PWD}/../../place_net_ros:/colcon_ws/src/place_net_ros
      # The docker entrypoints
      - ${PWD}/entrypoints:/place_net/docker/entrypoints
      # mount the X11 socket to enable graphics display
      - /tmp/.X11-unix:/tmp/.X11-unix
      # required for non-nvidia users, comment out for nvidia users
      - /dev/dri:/dev/dri
      # add the .Xauthority file to use ssh X11 forwarding
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - ${HOME}/.cache/torch:/torch_cache
    environment:
      - PLACE_NET_CONFIG
      # pass the display variable to the container
      - DISPLAY=${DISPLAY}
      # Enable the GPU for all purposes (without this line, OpenGL uses CPU rendering with llvmpipe)
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility
      - TORCHINDUCTOR_CACHE_DIR=/torch_cache/torchinductor
      - TORCHINDUCTOR_FX_GRAPH_CACHE=/torch_cache/fx_graph_cache
      - TORCHDYNAMO_CACHE_DIR=/torch_cache/dynamo
      - CUDA_HOME=/usr/local/cuda
      - CUDA_PATH=/usr/local/cuda
      - CPATH=/usr/local/cuda/include
      - TRITON_PTXAS_PATH=/usr/local/cuda/bin/ptxas
    network_mode: host
    ipc: host
    pid: host

  generate_task_poses:
    extends: place_net_runtime
    container_name: place_net_task_pose_generation
    entrypoint: /place_net/docker/entrypoints/generate_task_poses.sh

  calculate_ground_truth:
    extends: place_net_runtime
    container_name: place_net_ground_truth_calculation
    entrypoint: /place_net/docker/entrypoints/calculate_ground_truth.sh

  train_model:
    extends: place_net_runtime
    container_name: place_net_training
    entrypoint: /place_net/docker/entrypoints/train_model.sh

  generate_irm:
    extends: place_net_runtime
    container_name: place_net_inverse_reachability_map_generation
    entrypoint: /place_net/docker/entrypoints/generate_irm.sh

  ros_server:
    extends: place_net_runtime
    container_name: place_net_ros_server
    entrypoint: /place_net/docker/entrypoints/launch_ros_server.sh
    volumes:
      - ${PLACE_NET_PARAMS_FILE:-/dev/null}:/place_net_ros_params.yaml
      - ${PLACE_NET_IRM_FILE:-/dev/null}:/place_net_irm.pt
      - ${PLACE_NET_MODEL_FILE:-/dev/null}:/place_net_model.pt
      - ${PLACE_NET_MODEL_FILE:-/dev/null}/../config.yaml:/config.yaml
      - ${CYCLONEDDS_URI:-/dev/null}:/cyclonedds.xml
    environment:
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI=/cyclonedds.xml
      - ROS_DOMAIN_ID