pointclouds:
  living_room_small:
    elevation: 0.1
    regions:
      - {min_bound: [-2.52, -1.95, 0.20], max_bound: [2.41, 4.01, 2.0]}

  attic-draft:
    regions: 
      - {min_bound: [-4.0, -3.85, 0.0], max_bound: [-0.5, 3.2, 2.0]}
      - {min_bound: [ 1.4, -3.85, 0.0], max_bound: [ 4.7, 3.2, 2.0]}
      - {min_bound: [-5.5, -2.30, 0.0], max_bound: [ 5.8, 2.0, 2.1]}
      - {min_bound: [ 5.8, -3.80, 0.0], max_bound: [ 8.5, 2.0, 2.1]}

  URSA_sample_valves:
    elevation: -1.0
    regions: 
      - {min_bound: [-3.7, -3.8, 0.0], max_bound: [3.9, 4.0, 2.0]}

  geometry_env: {}

  office:
    regions: 
      - {min_bound: [-3.8, -2.6, 0.0], max_bound: [3.8, 2.6, 2.0]}

  nrg_map:
    filter_statistical_outliers: True
    filter_std_dev: 1.1
    filter_num_neighbors: 30
    regions:
      - {center: [-4.2, 0.0, 1.1], extent: [9, 18, 1.8], yaw: -23}
      - {center: [-11.5, -1, 1.1], extent: [5.5, 6.0, 1.8], yaw: -23}

pointcloud_data_path: "base_net/data/pointclouds/"
task_data_path: "base_net/data/tasks/"
solution_data_path: "base_net/data/solutions/"
fake_solutions: False

curobo_config_file:
  ros_package: spot_curobo_config
  path: config/spot.xrdf

urdf_file:
  ros_package: spot_description
  path: urdf/spot.urdf.xacro
  xacro_args: 'has_eap:=True has_arm:=True'

task_geometry:
  base_link_elevation: 0.709
  min_pointcloud_elevation: 0.2
  robot_reach_radius: 0.9
  workspace_radius: 2.0
  position_count: 20
  heading_count: 20
  check_environment_collisions: True

task_generation:
  max_ik_count: 500
  counts:
    empty: [100, 50, 20]
    surface: 300
    close: 300
    far: 300
    offset: 100
  surface_offset: 0.15
  min_offsets:
    surface: 0.10
    close: 0.15
    far: 0.40
  max_offsets: 
    close: 0.30
    far: 0.90

model_settings:
  pointcloud_encoder: 'PointNet'
  loss_function: 'Dice' # BCE, Dice, Focal
  cuda_device: 0
  batch_size: 2
  learning_rate: 0.0005
  debug: False
  log_base_path: 'base_net/data/runs/latest/'
  checkpoint_base_path: 'base_net/data/checkpoints/'
  checkpoint_frequency: 50