pointclouds:
  - {path: "base_net/data/pointclouds/attic-draft.pcd", elevation: 0.0}
  - {path: "base_net/data/pointclouds/URSA_sample_valves.pcd", elevation: -1.0}
  - {path: "base_net/data/pointclouds/geometry_env.pcd", elevation: 0.0}

task_data_path: "base_net/data/tasks/"
solution_data_path: "base_net/data/solutions"

curobo_config_file:
  ros_package: spot_curobo_config
  path: config/spot.xrdf

urdf_file:
  ros_package: spot_description
  path: urdf/spot.urdf.xacro
  xacro_args: 'has_eap:=True has_arm:=True'

task_geometry:
  base_link_elevation: 0.709
  min_pointcloud_elevation: 0.05
  robot_reach_radius: 0.9
  workspace_radius: 2.0
  surface_task_offset: 0.15
  position_count: 20
  heading_count: 20
  check_environment_collisions: False

task_generation:
  max_ik_count: 2000
  counts:
    surface: 0
    close: 0
    far: 1000
    offset: 100
  surface_offset: 0.15
  min_offsets:
    surface: 0.10
    close: 0.15
    far: 0.60
  max_offsets: 
    close: 0.30
    far: 0.90

model_settings:
  pointcloud_encoder: 'PointNet'
  cuda_device: 0
  batch_size: 10
  learning_rate: 0.0005
  debug: False