pointclouds:
  - {path: "base_net/data/pointclouds/URSA_sample_valves.pcd", elevation: -1.0}


task_path: "base_net/data/tasks/"

curobo_config_file:
  ros_package: spot_curobo_config
  path: config/spot.xrdf

urdf_file:
  ros_package: spot_description
  path: urdf/spot.urdf.xacro
  xacro_args: 'has_eap:=True has_arm:=True'

cuda_device: 0
end_effector_elevation: 0.709
robot_reach_radius: 0.9
obstacle_inclusion_radius: 2.0
position_count: 15
yaw_count: 15
close_point_offset: 0.15