services:
  base_net:
    environment:
      # Load in the ROS distro
      - ROS_DISTRO=$TARGET_ROS_DISTRO
    runtime: nvidia
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    container_name: base_net_${BUILD_TARGET}_dev
    image: alexnavtt/base_net:${BUILD_TARGET}
    build:
      context: ./..
      dockerfile: docker/Dockerfile
      ssh:
        - default
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
        NO_PROXY: $NO_PROXY
        http_proxy: $http_proxy
        https_proxy: $https_proxy
        no_proxy: $no_proxy
        ROS_DISTRO: $TARGET_ROS_DISTRO
        BUILD_TARGET: $BUILD_TARGET
        CUDA_VERSION: $TARGET_CUDA_VERSION

  generate_task_poses:
    extends: base_net
    container_name: base_net_task_pose_generation
    volumes:
      - ${PWD}/../../base_net:/base_net
    command: "/bin/bash -l -c 'base_net generate-task-poses --config-file base_net/config/${BASE_NET_CONFIG}'"

  calculate_ground_truth:
    extends: base_net
    container_name: base_net_ground_truth_calculation
    volumes:
      - ${PWD}/../../base_net:/base_net
    command: "/bin/bash -l -c 'base_net calculate-ground-truth --config-file base_net/config/${BASE_NET_CONFIG}'"

  train_model:
    extends: base_net
    container_name: base_net_training
    volumes:
      - ${PWD}/../../base_net:/base_net
    command: "/bin/bash -l -c 'base_net train --config-file base_net/config/${BASE_NET_CONFIG}'"

  