services:
  base_net:
    environment:
      # pass the display variable to the container
      - DISPLAY=${DISPLAY}
      # disable qt-X11 memory sharing for RViz
      - QT_X11_NO_MITSHM=1
      # Load in the ROS distro
      - ROS_DISTRO=$TARGET_ROS_DISTRO
      # Get the build target
      - BUILD_TARGET=$BUILD_TARGET
    security_opt:
      # this is set bc of errors with RViz being denied dbus comm w/ host
      - apparmor:unconfined
    volumes:
      # mount the X11 socket to enable graphics display
      - /tmp/.X11-unix:/tmp/.X11-unix
      # required for non-nvidia users, comment out for nvidia users
      # - /dev/dri:/dev/dri
      # add the .Xauthority file to use ssh X11 forwarding
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      # The base net folder itself
      - ${PWD}/../../base_net:/base_net
    runtime: nvidia
    # give the container access to the host's network
    ## network_mode: host
    ## ipc: host
    ## pid: host
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    container_name: base_net_${BUILD_TARGET}_dev
    image: alexnavtt/base_net:${BUILD_TARGET}
    build:
      context: ./..
      dockerfile: docker/Dockerfile
      # platforms: 
      #   - linux/${BUILD_ARCHITECTURE}
      ssh:
        - default
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
        NO_PROXY: $NO_PROXY
        http_proxy: $http_proxy
        https_proxy: $https_proxy
        no_proxy: $no_proxy
        ROS_DISTRO: $TARGET_ROS_DISTRO
        BUILD_TARGET: $BUILD_TARGET
        CUDA_VERSION: $TARGET_CUDA_VERSION


  