# QueryBaseLocation.srv

## Request

# The full set of poses for the robot end effector
geometry_msgs/PoseArray end_effector_poses

# The pointcloud representation of the collision environment. 
sensor_msgs/PointCloud2 pointcloud

# The name of the link for which the base poses should be returned
string base_link

# Whether or not to use ground truth calculations. Keep in mind that
# the ground truth can take over a minute PER END EFFECTOR POSE to 
# complete, and is mainly intended for testing and debugging
bool ground_truth false

---

## Response

# Response poses will be defined in the same frame as the request pointcloud

# Whether or not there was at least one valid pose
bool has_valid_pose

# The base pose with the optimal positioning
geometry_msgs/PoseStamped optimal_base_pose

# Indices of the task poses which can be reached from the optimal base pose
int64[] valid_task_indices

# The score of the optimal pose in the range [0, 1]
float32 optimal_score

# All valid poses for the robot base link
geometry_msgs/PoseArray valid_poses

# Scores for each valid pose in order
float32[] valid_pose_scores