# QueryReachablePoses.srv

# Given a robot base pose, an environment pointcloud, and a set of
# end effector poses, determine which end effectors poses can be 
# reached from that base pose using one of the BaseNet model, the
# inverse reachability map, or direct IK calculations

## Request

# The full set of poses for the robot end effector
geometry_msgs/PoseArray end_effector_poses

# The pointcloud representation of the collision environment.
sensor_msgs/PointCloud2 pointcloud

# Filter std deviation for the pointcloud. If 0, no filtering is done
float32 filter_std_dev 0.0

# The pose of the link for which the reachability will be calculated
# This link should be statically attached to the model base link
string link_frame
geometry_msgs/PoseStamped link_pose

## IK Solver Params for the ground truth method
float64 rotation_threshold 0.01
float64 position_threshold 0.001
int64 num_seeds 10
bool check_self_collision true

# The mode for ground truth calculations.
# Options are [model, irm, ground_truth]
string mode "model" 

---

## Response

# Whether the call was made successfully
bool success

# The indices of the input task poses which are reachable
int64[] valid_task_indices