# QueryReachablePosesGT.srv

# Given a robot base pose, an environment pointcloud, and a set of
# end effector poses, determine which end effectors poses can be 
# reached from that base pose using the BaseNet model

## Request

# The full set of poses for the robot end effector
geometry_msgs/PoseArray end_effector_poses

# The pointcloud representation of the collision environment.
sensor_msgs/PointCloud2 pointcloud

# Filter std deviation for the pointcloud. If 0, no filtering is done
float32 filter_std_dev 0.0

# The pose of the link for which the reachability will be calculated
# This link should be statically attached to the model base link
string link_frame
geometry_msgs/PoseStamped link_pose

---

## Response

# Whether the call was made successfully
bool success

# The indices of the input task poses which are reachable
int64[] valid_task_indices