pointclouds:
  - {path: "../test_data/room_scan1.pcd", elevation: -1.35}
  - {path: "../test_data/room_scan2.pcd", elevation: -1.35}

tasks: 
  - {pointcloud: "room_scan1", position: [20.0, 0.0, 0.6], orientation: [1, 0, 0, 0]}
  - {pointcloud: "room_scan2", position: [1.0, 0.5, 1.0], orientation: [-0.8535534, -0.1464466, 0.3535534, 0.3535534]}

curobo_config_file:
  ros_package: spot_curobo_config
  path: spot_curobo.yaml

urdf_file:
  ros_package: spot_description
  path: urdf/spot.urdf.xacro
  xacro_args: 'has_eap:=True has_arm:=True'

cuda_device: 0