pointclouds:
  wooden_chair: {}
  living_room_small: {elevation: 0.1}
  attic-draft: {}
  URSA_sample_valves: {elevation: -1.0}
  geometry_env: {}
  office: {}
  kitchen: {elevation: 0.15}
  nrg_map: {filter_statistical_outliers: True, filter_std_dev: 1.1, filter_num_neighbors: 30}
  hallways: {filter_statistical_outliers: True, filter_std_dev: 1.1, filter_num_neighbors: 30}
  apartment: {filter_statistical_outliers: True, filter_std_dev: 1.1, filter_num_neighbors: 30}

pointcloud_data_path: "base_net/data/pointclouds/"
task_data_path: "base_net/data/tasks/"
solution_data_path: "base_net/data/solutions/"
fake_solutions: False
max_ik_count: null
debug: False

curobo_config_file:
  ros_package: spot_curobo_config
  path: config/spot.xrdf

urdf_file:
  ros_package: spot_description
  path: urdf/spot.urdf.xacro
  xacro_args: 'has_rl_kit:=True has_arm:=True'

unused_joint_defaults:
  front_left_hip_x  : -0.0058014001697301865
  front_left_hip_y  :  0.7929132580757141
  front_left_knee   : -1.5593334436416626
  front_right_hip_x : -0.007982775568962097
  front_right_hip_y :  0.7943171262741089
  front_right_knee  : -1.5458697080612183
  rear_left_hip_x   :  0.0062673864886164665
  rear_left_hip_y   :  0.7941105961799622
  rear_left_knee    : -1.5512280464172363
  rear_right_hip_x  :  0.012335322797298431
  rear_right_hip_y  :  0.8197641372680664
  rear_right_knee   : -1.55510675907135
  arm0_fingers      : -0.010957598686218262
  body_height_joint : 0.52
  body_yaw_joint    : 0.0
  body_pitch_joint  : 0.0
  body_roll_joint   : 0.0
  
task_geometry:
  base_link_elevation: 0.709
  max_radial_reach: 0.9
  min_task_elevation: 0.3
  max_task_elevation: 1.6
  min_pointcloud_elevation: 0.2
  max_pointcloud_elevation: 1.7
  max_pointcloud_radius: 2.0

task_generation:
  visualize: False
  surface_points: 
    offset: 0.15
    min_clearance: 0.0
    density: 5
  offset_points:
    - {name: 'close', offset_bounds: [0.15, 0.30], density: 5} 
    - {name: 'far'  , offset_bounds: [0.40, 0.90], density: 5} 
  pointcloud_regions:
    wooden_chair:
        - {min_bound: [-1.0, -1.0, 0.0], max_bound: [1.0, 1.0, 2.0]}
    living_room_small:
      - {min_bound: [-2.52, -1.95, 0.20], max_bound: [2.41, 4.01, 2.0]}
    attic-draft:
      - {min_bound: [-4.0, -3.85, 0.0], max_bound: [-0.5, 3.2, 2.0]}
      - {min_bound: [ 1.4, -3.85, 0.0], max_bound: [ 4.7, 3.2, 2.0]}
      - {min_bound: [-5.5, -2.30, 0.0], max_bound: [ 5.8, 2.0, 2.1]}
      - {min_bound: [ 5.8, -3.80, 0.0], max_bound: [ 8.5, 2.0, 2.1]}
    URSA_sample_valves:
      - {min_bound: [-3.7, -3.8, 0.0], max_bound: [3.9, 4.0, 2.0]}
    office:
      - {min_bound: [-3.8, -2.6, 0.0], max_bound: [3.8, 2.6, 2.0]}
    nrg_map:
      - {center: [-4.2, 0.0, 1.1], extent: [9, 18, 1.8], yaw: -23}
      - {center: [-11.5, -1, 1.1], extent: [5.5, 6.0, 1.8], yaw: -23}
    hallways:
      - {center: [  3.0,  -7.6, 1.1], extent: [ 8.0,  2.2, 1.8], yaw:  12}
      - {center: [  5.0,  -9.0, 1.1], extent: [ 4.0,  2.2, 1.8], yaw: -33}
      - {center: [  7.0,  -9.0, 1.1], extent: [ 6.5,  1.2, 1.8], yaw: -78}
      - {center: [  7.7, -20.0, 1.1], extent: [21.0,  2.2, 1.8], yaw: -80}
      - {center: [  6.0, -22.4, 1.1], extent: [ 2.5,  1.5, 1.8], yaw:  12}
      - {center: [ 10.0, -25.8, 1.1], extent: [ 1.5,  1.5, 1.8], yaw:  12}
      - {center: [-14.5, -37.5, 1.1], extent: [ 6.0, 12.0, 1.8], yaw:  12}
      - {center: [ -9.5, -34.0, 1.1], extent: [ 5.0,  7.0, 1.8], yaw:  12}
      - {center: [  0.0, -34.5, 1.1], extent: [18.0,  2.0, 1.8], yaw:  12}
      - {center: [ 10.8, -32.5, 1.1], extent: [ 4.0,  5.0, 1.8], yaw:  12}
    apartment:
      - {center: [12.0, -20.5, 1.1], extent: [18.0,  7.0, 1.8], yaw:  -78}
    kitchen:
      - {min_bound: [-1.5, -2.0, 1.0], max_bound: [1.5, 2.7, 2.0]}
      - {min_bound: [-1.5, -1.5, 0.0], max_bound: [1.5, 2.7, 2.0]}

inverse_reachability_map:
  task_resolution: 
    z: 100
    pitch: 50
    roll: 20

  solution_resolution:
    x: 20
    y: 20
    yaw: 20

model_settings:
  # Configuration params
  pointcloud_encoder: 'PointNet'
  loss_function: 'Focal' # BCE, Dice, Focal, Tversky
  use_normals: False
  external_classifier: False
  downsample_fraction: 0.5
  pointcloud_noise_stddev: 0.04

  # Hyperparameters
  feature_size: 1024
  channel_count: 512
  data_split: [80, 20, 0]
  num_epochs: 2000
  batch_size: 16
  learning_rate: 0.001
  patience: 150
  mlp_dropout: 0.5
  convolution_dropout: 0.3

  # Loss-function specific hyperparameters
  tversky_loss: {'alpha': 0.8, 'beta': 0.2}
  bce: {'pos_weight': 5.0}
  focal_loss: {'pos_weight': 5.0}
  
  # System parameters
  cuda_device: 0
  log_base_path: 'base_net/data/runs/v0.7.2/'
  checkpoint_base_path: 'base_net/data/checkpoints/v0.7.2/'
  checkpoint_frequency: 200

